config/routes.rb
Rails.application.routes.draw do

  resources :slides
  resources :sponsors
  get 'styleguide' => 'styleguide#index' if Rails.env.development?
  get 'player_matches/confirm_call/:id/:m_id', to: "player_matches#confirm_call", as: "player_confirm_call"

  get 'player_matches/deny_call/:id/:m_id', to: "player_matches#deny_call", as: "player_deny_call"

  resources :documents
  resources :schools

  get 'player_team_seasons/index'
  get 'player_team_seasons/show'

  resources :posts
  resources :photos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :coaches, :controllers => {:sessions => "coaches/sessions", :registrations => "coaches/registrations"}, skip: :registrations
  devise_scope :coach do
    resource :registration,
      only: [:edit, :update, :destroy],
      path: 'coaches',
      path_names: { new: 'sign_up' },
      controller: 'coaches/registrations',
      as: :coach_registration do
        get :cancel
    end
  end


  devise_for :player_auths,  :controllers => {:registrations => "player_auths/registrations", :confirmations => "player_auths/confirmations", :sessions => "player_auths/sessions"}, skip: :registrations
  devise_scope :player_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'player_auth',
      path_names: { new: 'sign_up' },
      controller: 'player_auths/registrations',
      as: :player_auth_registration do
        get :cancel
      end
  end
  as :player_auth do
      patch '/player_auths/confirmation' => 'player_auths/confirmations#update', :via => :patch, :as => :update_player_confirmation
  end


  devise_for :guardian_auths,  :controllers => {:registrations => "guardian_auths/registrations", :confirmations => "guardian_auths/confirmations", :sessions => "guardian_auths/sessions"}, skip: :registrations
  devise_scope :guardian_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'guardian_auth',
      path_names: { new: 'sign_up' },
      controller: 'guardian_auths/registrations',
      as: :guardian_auth_registration do
        get :cancel
      end
  end

  as :guardian_auth do
      patch '/guardian_auths/confirmation' => 'guardian_auths/confirmations#update', :via => :patch, :as => :update_guardian_confirmation
  end


  resources :statistics
  resources :matches
  resources :competitions
  # Descomentar para EuroLeague
  # resources :seasons
  resources :teams
  resources :exams
  resources :guardians
  # resources :players
  resources :guardian_team_seasons, only: [:index, :show, :update]
  resources :guardian_auth_matches, only: [:update]
  resources :player_team_seasons, only: [:index, :show, :update]

  get 'guardian_auth_matches/confirm_call/:id/:m_id', to: "guardian_auth_matches#confirm_call", as: "guardian_confirm_call"
  get 'guardian_auth_matches/deny_call/:id/:m_id', to: "guardian_auth_matches#deny_call", as: "guardian_deny_call"


  resources :team_seasons do
    collection do
      get ':id/attendance', to: 'team_seasons#attendance', as: 'attendance'
    end
  end


  resources :practices do
    collection do
      post 'update_player_practice/:id', to: 'practices#update_player_practice', as: 'update_player_practice'
      post 'add_pp_late_time/:id', to: 'practices#add_late_time', as: "add_pp_late_time"
    end
  end

  get 'attendance/show/:id', to: 'attendance#show', as: 'show_attendance'

  get 'guardian_auth_players/index', as: 'guardian_index_players'
  get 'guardian_edit_player/:id', to: 'guardian_auth_players#edit', as: 'guardian_edit_player'
  post 'guardian_update_player/:id', to: 'guardian_auth_players#update', as: 'guardian_update_player'
  patch 'guardian_update_player/:id', to: 'guardian_auth_players#update'
  get 'guardian_show_player/:id', to: 'guardian_auth_players#show', as: 'guardian_show_player'

  get 'coach_guardians/edit'
  get 'coach_guardians/new'

  get 'coach_players/new', as: 'coach_new_player'
  get 'coach_players/index', to: 'coach_players#index', as: 'coach_index_players'
  get 'coach_show_player/:id', to: 'coach_players#show', as: 'coach_show_player'
  get 'coach_edit_player/:id', to: 'coach_players#edit', as: 'coach_edit_player'
  post 'coach_update_player/:id', to: 'coach_players#update', as: 'coach_update_player'
  patch 'coach_update_player/:id', to: 'coach_players#update'
  post 'coach_create_player', to: 'coach_players#create', as: 'coach_create_player'
  post 'coach_add_player_medical/:id', to: 'coach_players#add_medical', as: 'coach_add_medical'

  get 'coach_approved_photos/', to: 'photos#index_approved', as: 'index_approved'
  get 'coach_pending_photos/', to: 'photos#index_pending', as: 'index_pending'

  get 'general_pages/index', to: 'general_pages#index', as: 'general_index'
  get 'general_pages/contact', to: 'general_pages#contact', as: 'contact'
  post 'general_pages/send_contact', to: 'general_pages#send_contact', as: 'send_contact'
  get 'general_pages/about', to: 'general_pages#index', as: 'about'
  get 'general_pages/all_teams', to: 'general_pages#teams', as: 'all_teams'
  get 'general_pages/players/:id', to: 'general_pages#players', as: 'team_players'
  get 'general_pages/player/:id/:p_id', to: 'general_pages#player', as: 'gp_player'
  get 'general_pages/rankings/(:id/:c_id)', to: 'general_pages#rankings', as: 'ranking'
  get 'general_pages/calendar/:id/(:c_id)', to: 'general_pages#calendar', as: 'calendar'
  # get 'general_pages/competitions/(:id)', to: 'general_pages#competitions', as: 'all_competitions'
  # get 'general_pages/competition/:id/:c_id', to: 'general_pages#competition', as: 'show_competition'
  get 'general_pages/gallery/(team_season/:id)(/level/:level)', to: 'general_pages#photo_gallery', as: 'gallery'
  get 'general_pages/posts/(team_season/:id)(/level/:level)', to: 'general_pages#posts', as: 'all_posts'
  get 'general_pages/posts/:post_id(/team_season/:id)', to: 'general_pages#post', as: 'show_post'
  get 'general_pages/match/:m_id/team_season/:id', to: 'general_pages#match', as: 'show_match'

  post 'general_pages/change_season', to: 'general_pages#change_season', as: 'change_season'

  get 'list_documents', to: 'documents#show_documents', as: "list_documents"

  post 'add_stat_late_time/:id', to: 'statistics#add_late_time', as: "add_stat_late_time"

  get 'filter_team_seasons/:id', to: 'competitions#filter_team_seasons', as: 'filter_team_seasons'

  get 'get_team_level/:id', to: 'team_seasons#get_team_level', as: 'get_team_level'

  root 'general_pages#index'
end

app/models/team_season.rb
class TeamSeason < ActiveRecord::Base
  belongs_to :team

  belongs_to :season

  has_many :player_seasons
  has_many :players, :through => :player_seasons

  has_and_belongs_to_many :competitions

  has_many :away_matches, class_name: "Match", foreign_key: "away_team_id"
  has_many :home_matches, class_name: "Match", foreign_key: "home_team_id"
  has_and_belongs_to_many :coaches

  has_many :practices

  has_many :photos
  #has_and_belongs_to_many :photos

  has_and_belongs_to_many :posts

  has_and_belongs_to_many :sponsors
  accepts_nested_attributes_for :coaches, allow_destroy: true

  accepts_nested_attributes_for :player_seasons, allow_destroy: true

  accepts_nested_attributes_for :team

  accepts_nested_attributes_for :photos, allow_destroy: true
  # accepts_nested_attributes_for :player_seasons, allow_destroy: true

  validates_presence_of :team_id
  validates_presence_of :season_id

  has_attached_file :icon, styles: { medium: "300x300#", thumb: "100x100#", minithumb: "40x40#" },
    default_url: "/images/:style/missing.jpg",
    :convert_options => {
      :large => "-quality 80 -interlace Plane",
      :thumb => "-quality 80 -interlace Plane"
    },
    processors: [:thumbnail, :compression]
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\Z/


  has_attached_file :photo, styles: { banner: "1337x300#", medium: "300x300#"},
    default_url: "/images/:style/missing.jpg",
    :convert_options => {
      :large => "-quality 80 -interlace Plane",
      :thumb => "-quality 80 -interlace Plane"
    },
    processors: [:thumbnail, :compression]

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def self.search(search, season)
    joins(:team).where('season_id = :season and teams.name ILIKE :search', search: "%#{search}%", season: season.id )
  end

  def statistics(competition, start_date, end_date)
    if competition
      stats = initialize_stats()

      if start_date == nil && end_date == nil
        home_matches = self.home_matches.where(competition_id: competition.id)
        away_matches = self.away_matches.where(competition_id: competition.id)
      else
        home_matches = self.home_matches.where(match_date: start_date..end_date, competition_id: competition.id)
        away_matches = self.away_matches.where(match_date: start_date..end_date, competition_id: competition.id)
      end


      stats = calculate_stats(stats, home_matches, away_matches)


      return stats
    else
      stats = initialize_stats()

      if start_date == nil && end_date == nil
        home_matches = self.home_matches
        away_matches = self.away_matches
      else
        home_matches = self.home_matches.where(match_date: start_date..end_date)
        away_matches = self.away_matches.where(match_date: start_date..end_date)
      end


      stats = calculate_stats()



      return stats
    end
  end

  private
    def initialize_stats
      stats = Hash.new
      stats[:points] = 0
      stats[:losses] = 0
      stats[:wins] = 0
      stats[:draws] = 0
      stats[:goal_diff] = 0
      stats[:goals_for] = 0
      stats[:goals_against] = 0
      stats[:played] = 0

      return stats
    end

    def calculate_stats(stats, home_matches, away_matches)
      home_matches.each do |h_match|
        if h_match.home_goals == h_match.away_goals
          stats[:points] += 1
          stats[:draws] += 1
        elsif h_match.home_goals > h_match.away_goals
          stats[:points] += 3
          stats[:wins] += 1
        else
          stats[:losses] += 1
        end
        stats[:goals_for] += h_match.home_goals >= 0  ? h_match.home_goals : 0
        stats[:goals_against] += h_match.away_goals >= 0  ? h_match.away_goals : 0
      end

      away_matches.each do |a_match|
        if a_match.away_goals == a_match.home_goals
          stats[:points] += 1
          stats[:draws] += 1
        elsif a_match.away_goals > a_match.home_goals
          stats[:points] += 3
          stats[:wins] += 1
        else
          stats[:losses] += 1
        end
        stats[:goals_for] +=  a_match.away_goals >= 0  ? a_match.away_goals : 0
        stats[:goals_against] += a_match.away_goals >= 0  ? a_match.away_goals : 0
      end


      stats[:goal_diff] = stats[:goals_for] - stats[:goals_against]
      stats[:played] = home_matches.size + away_matches.size
      return stats
    end


end

app/controllers/team_seasons_controller.rb
class TeamSeasonsController < ApplicationController
  before_action :authenticate_coach!
  layout 'admin'
  before_action :set_team_season, only: [:show, :edit, :update, :destroy, :attendance]
  before_action :check_is_coach, only: [:edit]
  # GET /team_seasons
  # GET /team_seasons.json
  def index

    params.permit(:search)

    if session.has_key?(:current_season)
      @season = Season.find(session[:current_season])
    else
      @season = Season.last
    end

    if params[:search]
      @team_seasons = Kaminari.paginate_array(current_coach.team_seasons.includes(:team, :season).search(params[:search], @season)).page(params[:page]).per(30)
    else
      @team_seasons = current_coach.team_seasons.includes(:team, :season).where(season_id: @current_season.id).page(params[:page]).per(30)
    end
  end

  def attendance
    params.permit(:matches, :practices, :stats)

    @start_date = DateTime.now.beginning_of_month
    @end_date = DateTime.now.end_of_month


    if params.has_key?(:matches) || params.has_key?(:practices)
      if !params[:matches]
        matches = @team_season.away_matches.where(match_date: @start_date..@end_date) + @team_season.home_matches.where(match_date: @start_date..@end_date)
        matches = matches.sort_by{|e| e.match_date}
        @show_matches = false
      else
        matches = []
        @show_matches = true
      end

      if !params[:practices]
        practices = @team_season.practices.where(practice_date: @start_date..@end_date).order(:practice_date)
        @show_practices = false
      else
        practices = []
        @show_practices = true
      end
    else
      matches = @team_season.away_matches.where(match_date: @start_date..@end_date) + @team_season.home_matches.where(match_date: @start_date..@end_date)
      matches = matches.sort_by{|e| e.match_date}
      practices = @team_season.practices.where(practice_date: @start_date..@end_date).order(:practice_date)
    end

    if params.has_key?(:stats) && params[:stats]
      @stat = true
    elsif params.has_key?(:stats) && !params[:stats]
      @stat = false
    end

    @players = @team_season.players.order(:name)
    @elements = practices.map{|f| [f.practice_date, false, f.id]}
    @elements = @elements + matches.map{|f| [f.match_date, true, f.id]}
    @elements = @elements.sort_by{|e| e[0]}


  end

  def get_team_level
     @level = Team.find(params[:id]).level
  end

  # GET /team_seasons/1
  # GET /team_seasons/1.json
  def show

  end

  # GET /team_seasons/new
  def new
    @team_season = TeamSeason.new
  end

  # GET /team_seasons/1/edit
  def edit
  end

  # POST /team_seasons
  # POST /team_seasons.json
  def create
    @team_season = TeamSeason.new(team_season_params)

    respond_to do |format|
      if @team_season.save
        format.html { redirect_to @team_season, notice: 'Team season was successfully created.' }
        format.json { render :show, status: :created, location: @team_season }
      else
        format.html { render :new }
        format.json { render json: @team_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_seasons/1
  # PATCH/PUT /team_seasons/1.json
  def update
    # if team_season_params.has_key?(:photos_attributes)
      # team_season_params[:photos_attributes].each do |photo|
        # @photo.team_season.photos.each do |photo|
        #   photo.update_attributes(main: false)
        # end
      # end
    # end
    respond_to do |format|
      if @team_season.update(team_season_params)
        format.html { redirect_to @team_season, notice: 'Team season was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_season }
      else
        format.html { render :edit }
        format.json { render json: @team_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_seasons/1
  # DELETE /team_seasons/1.json
  def destroy
    @team_season.destroy
    respond_to do |format|
      format.html { redirect_to team_seasons_url, notice: 'Team season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_is_coach
      if !@team_season.coaches.exists?(current_coach.id)
        flash[:notice] = "This team is not yours!"
        redirect_to team_seasons_path
      end
    end

    def set_team_season
      @team_season = TeamSeason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_season_params
      params.require(:team_season).permit(:team_id, :season_id, :photo, :icon, :permission, player_seasons_attributes:[:shirt_number, :shoe_size, :shirt_name, :player_id, :_destroy,:id], coach_ids: [], photos_attributes: [:id, :title, :description, :match_id, :photo, :level, :approved, :main, :video, :video_url,  :private,  :_destroy])
    end
end

app/helpers/team_seasons_helper.rb
module TeamSeasonsHelper

  def get_state(state)
    if state == nil
      t("strings.states.none")
    else
      get_states[state]
    end
  end

  def get_state_initial(state)
    if state == nil
      "N"
    else
      get_states[state][0]
    end
  end

  def get_states
    states = [  I18n.t("strings.states.none"),
                I18n.t("strings.states.present"),
                I18n.t("strings.states.miss"),
                I18n.t("strings.states.late"),
                I18n.t("strings.states.called"),
                I18n.t("strings.states.called_confirmed"),
                I18n.t("strings.states.called_denied")
              ]
  end

  def state_none()
    0
  end

  def state_presence()
    1
  end

  def state_fault()
    2
  end

  def state_late()
    3
  end

  def state_called_no_answer()
    4
  end

  def state_called_confirmed()
    5
  end

  def state_called_denied()
    6
  end


  def get_states_options
    array = []
    i=0
    get_states.each do |state|
      array.push([state,i])
      i+=1
    end
    array
  end

  def get_state_colors(state)
    states = [  '#6666CC',
                '#0cb329',
                '#ff0000',
                '#e26e34',
                '#87ddff',
                '#00aaff',
                '#a9a9a9']
    if state == nil
      return states[0]
    else
      return states[state]
    end
  end

  def get_permission(permission)
    get_permission_types[permission]
  end

  def get_permission_types
    kinds = [t("strings.permissions.all_team"),
            t("strings.permissions.player_only")]
  end


  def get_permissions
    array = []
    i=0
    get_permission_types.each do |kind|
      array.push([kind, i])
      i+=1
    end
    array
  end
end

app/views/team_seasons/_attendance_stats_body.html.erb
<% get_states_options().each do |state| %>
  <% if state[1] != state_none()  && state[1] < state_called_no_answer() %>
    <td class="right"><%= stats[""+state[1].to_s]%></td>
  <% else %>
    <td></td>
  <% end %>
<% end %>

<td><%= stats[:played] %></td>
<td><%= stats[:goals] %></td>
<td><%= stats[:penalties] %></td>
<td><%= stats[:assists] %></td>
<td><%= stats[:played_minutes] %></td>
<td><%= stats[:own_goals] %></td>
<td><%= stats[:yellows] %></td>
<td><%= stats[:red] %></td>
<td><%= stats[:stat_late_minutes] %></td>
<td><%= stats[:pp_late_minutes] %></td>

app/views/team_seasons/_attendance_stats_header.html.erb
<% get_states_options().each do |state| %>
  <% if state[1] > state_presence() && state[1] < state_called_no_answer() %>
    <th class="th-total"><%= get_state_initial(state[1].to_i)%></th>
  <% elsif state[1] == state_presence() %>
    <th class="th-total-first"><%= get_state_initial(state[1].to_i)%></th>
  <% else %>
    <th class="th-total"></th>
  <% end %>
<% end %>

<th class="th-stat">J</th>
<th class="th-stat">GM</th>
<th class="th-stat">GP</th>
<th class="th-stat">A</th>
<th class="th-stat">MJ</th>
<th class="th-stat">AG</th>
<th class="th-stat">A</th>
<th class="th-stat">V</th>
<th class="th-stat">Atraso T</th>
<th class="th-stat">Atraso J</th>

app/views/team_seasons/_form.html.erb
  <div class="box-body">
    <%= form_for(@team_season) do |f| %>
      <%= render partial: 'admin_partials/errors/errors_form', locals: { current_object: @team_season} %>

      <div class="form-group">
        <%= f.label :team %><br>
        <%= f.select :team_id, Team.all.collect {|p| [ p.name, p.id ] }, {}, class:"form-control", id: "team-select", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :icon %><br>
        <%= f.file_field :icon, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :main_photo %><br>
        <%= f.file_field :photo, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :permission %><br>
        <%= f.select :permission, options_for_select(get_permission_types()) , {}, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :season %><br>
        <%= f.select :season_id, Season.all.collect {|p| [ p.start_year.to_s + "/" + p.end_year.to_s, p.id ] }, {}, class:"form-control", required: true%>
      </div>

      <div class="form-group">
        <%= f.label :coaches %><br>
        <%= f.collection_select :coach_ids, Coach.all, :id, :name, {:include_blank => "No coach"}, {:multiple => true,class:"form-control", id:"coach-select"}  %>
      </div>
      <%#= f.add_nested_fields_link :player_seasons %>
      <div class="box box-info collapsed-box">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t("strings.team_season.player_season")%></h3>
          <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
          </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
          <%= f.nested_fields_for :player_seasons, wrapper_tag: :div, wrapper_options: { class: 'col-md-4' } do |ff| %>
            <% index = f.object.player_seasons.index(ff.object) %>
            <div class="box box-success box-solid">
              <div class="box-header with-border">
                <h3 class="box-title"><%= index ? t("activerecord.models.player") + " " + (index.to_i + 1).to_s : t("strings.player.new") %></h3>
                <div class="box-tools pull-right">
                  <%= ff.remove_nested_fields_link 'x', class: 'btn btn-box-tool', role: 'button', "data-widget" => "remove" %>
                </div>
                <!-- /.box-tools -->
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <div class="row">
                  <div class="form-group col-md-12">
                    <%= ff.label :player_id %><br>
                    <%= ff.select :player_id, Player.all.collect {|p| [ p.name, p.id ] }, {}, class:"form-control"%>
                  </div>
                </div>
                <div class="row">
                  <div class="form-group col-md-6">
                    <%= ff.label :shirt_name %><br>
                    <%= ff.text_field :shirt_name, class:"form-control" %>
                  </div>

                  <div class="form-group col-md-3">
                    <%= ff.label :shirt_number %><br>
                    <%= ff.number_field :shirt_number, class:"form-control" %>
                  </div>

                  <div class="form-group col-md-3">
                    <%= ff.label :shoe_size %><br>
                    <%= ff.number_field :shoe_size, class:"form-control" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          <%= f.add_nested_fields_link :player_seasons%>
        </div>
      </div>
                <!-- /.box-body -->



      <%# if (params[:action] == "edit" && guardian_auth_signed_in?) || coach_signed_in? %>
        <div class="box box-info collapsed-box">
          <div class="box-header with-border">
            <h3 class="box-title"><%= t("strings.team_season.photos")%></h3>
            <div class="box-tools pull-right">
              <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
            </div><!-- /.box-tools -->
          </div><!-- /.box-header -->
          <div class="box-body"  id="photos-nested">
            <%= f.nested_fields_for :photos, class: "nested-photo-form", wrapper_tag: :div, wrapper_options: { class: 'col-md-4' } do |fff| %>
              <div class="box box-success box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title"><%= t("strings.team_season.photo") %></h3>
                  <div class="box-tools pull-right">
                    <%= fff.remove_nested_fields_link %>
                  </div>
                    <!-- /.box-tools -->
                </div>
                  <!-- /.box-header -->

                    <%= fff.hidden_field :approved, value: true %>
                    <%= fff.hidden_field :private, value: true %>
                    <%= fff.hidden_field :team_season_id, value: @team_season.id %>

                    <% if params[:action] == "edit" %>
                      <%= fff.hidden_field :level, value: @team_season.team.level %>
                    <% else %>
                      <%= fff.hidden_field :level, value: "0", class: "team-level" %>
                    <% end %>

              <div class="box-body">
                <div class="row">
                  <div class="form-group col-md-12">
                    <p class="team-level-name"></p>
                  </div>
                    <% if fff.object.photo.exists? %>
                      <div class="form-group  col-md-12">
                        <%= image_tag fff.object.photo.url(:thumb) %>
                      </div>
                    <% end %>

                    <div class="form-group  col-md-12">
                      <%= fff.label :video %><br>
                      <%= fff.check_box :video, {class: "is-video"}  %>
                    </div>

                    <div class="photo-image">
                      <div class="form-group col-md-12">
                        <%= fff.label :photo %>
                        <%= fff.file_field :photo, class: "form-control" %>
                      </div>
                    </div>

                    <div class="video-url">
                      <!-- <div class="form-group col-md-12"> -->
                        <%#= fff.label :video_url %>
                        <%#= fff.text_field :video_url, class: "form-control" %>
                      <!-- </div> -->
                    </div>

                    <div class="form-group col-md-12">
                      <%= fff.label :title %>
                      <%= fff.text_field :title, class:"form-control"  %><br>
                    </div>
                    <div class="form-group col-md-12">
                      <%= fff.label :description %>
                      <%= fff.text_area :description, class:"form-control"  %><br>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            <%= f.add_nested_fields_link :photos %>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      <%# end %>
    <div class="box-footer">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>


<script>
  $(document).on('ready page:load', function(){
    $( "#coach-select" ).select2({});
  });

  $( "#team-select" ).on("change", function() {
    var teamId = $(this).val();
    $.ajax({
      url: '/get_team_level/' +teamId,
      type: 'GET'
    });
  });

  $("#photos-nested").on("fields_added.nested_form_fields", function(event, param){

    var added_field_id = param.added_index;

    var teamId = $("#team-select").val();

    $(event.target).find(".is-video").on("change", function(){
      if ($(this).is(':checked'))
      {

        $(this).parent().parent().find(".photo-image").html("");
        $(this).parent().parent().find(".video-url").html('<div class="form-group col-md-12"><label for="team_season_photos_attributes_'+added_field_id+'_video_url">Video URL</label><input class="form-control" type="text" value="" name="team_season[photos_attributes]['+added_field_id+'][video_url]" id="team_season_photos_attributes_'+added_field_id+'_video_url"></div>');
      }else {
        $(this).parent().parent().find(".photo-image").html('<div class="form-group col-md-12"><label for="team_season_photos_attributes_'+added_field_id+'_photo">Photo</label><input class="form-control" type="file" name="team_season[photos_attributes]['+added_field_id+'][photo]" id="team_season_photos_attributes_'+added_field_id+'_photo"></div>');
        $(this).parent().parent().find(".video-url").html('');

      }
    });

    if (teamId != ''){
      $.ajax({
        url: '/get_team_level/' +teamId,
        type: 'GET'
      });
    };
  });


</script>

app/views/team_seasons/get_team_level.js.erb
$(".team-level").val("<%=@level%>")
$(".team-level-name").html("<%=get_level(@level)%>")

app/views/team_seasons/show.html.erb
<%= render partial: 'admin_partials/show/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.team_season.show") } %>

<%= render "admin_partials/errors/notices" %>

          <strong><%= t("activerecord.attributes.team_season.photo") %></strong>
          <p class="text-muted">
            <%= image_tag @team_season.photo.url(:medium) %>
          </p>

          <strong><%= t("activerecord.attributes.team_season.team") %></strong>
          <p class="text-muted">
            <%= @team_season.team.name %> - <%= @team_season.season.start_year %>/<%= @team_season.season.end_year %>
          </p>

          <strong><%= t("activerecord.attributes.team_season.players") %></strong>
          <br>
          <p>
          |
          <% @team_season.players.each do |player| %>
            <span><%= link_to player.name, coach_show_player_path(player) %> | </span>
          <% end %>
          </p>

          <%= t("activerecord.attributes.team_season.photos") %>
          <br>
          <% @team_season.photos.where(video: false).each do |photo| %>
            <%= link_to photo.photo.url(:original) do %>
              <%= image_tag photo.photo.url(:thumb) %>
            <% end %>
          <% end %>
          <br>
          <%= t("activerecord.attributes.team_season.videos") %>
          <br>
          <% @team_season.photos.where(video: true).each do |photo| %>
            <%= link_to photo.title, photo.video_url %> <br>
          <% end %>

<%= render partial: 'admin_partials/show/footer', locals: {edit_path: edit_team_season_path(@team_season), back_path: team_seasons_path}%>