config/routes.rb
Rails.application.routes.draw do

  resources :slides
  resources :sponsors
  get 'styleguide' => 'styleguide#index' if Rails.env.development?
  get 'player_matches/confirm_call/:id/:m_id', to: "player_matches#confirm_call", as: "player_confirm_call"

  get 'player_matches/deny_call/:id/:m_id', to: "player_matches#deny_call", as: "player_deny_call"

  resources :documents
  resources :schools

  get 'player_team_seasons/index'
  get 'player_team_seasons/show'

  resources :posts
  resources :photos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :coaches, :controllers => {:sessions => "coaches/sessions", :registrations => "coaches/registrations"}, skip: :registrations
  devise_scope :coach do
    resource :registration,
      only: [:edit, :update, :destroy],
      path: 'coaches',
      path_names: { new: 'sign_up' },
      controller: 'coaches/registrations',
      as: :coach_registration do
        get :cancel
    end
  end


  devise_for :player_auths,  :controllers => {:registrations => "player_auths/registrations", :confirmations => "player_auths/confirmations", :sessions => "player_auths/sessions"}, skip: :registrations
  devise_scope :player_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'player_auth',
      path_names: { new: 'sign_up' },
      controller: 'player_auths/registrations',
      as: :player_auth_registration do
        get :cancel
      end
  end
  as :player_auth do
      patch '/player_auths/confirmation' => 'player_auths/confirmations#update', :via => :patch, :as => :update_player_confirmation
  end


  devise_for :guardian_auths,  :controllers => {:registrations => "guardian_auths/registrations", :confirmations => "guardian_auths/confirmations", :sessions => "guardian_auths/sessions"}, skip: :registrations
  devise_scope :guardian_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'guardian_auth',
      path_names: { new: 'sign_up' },
      controller: 'guardian_auths/registrations',
      as: :guardian_auth_registration do
        get :cancel
      end
  end

  as :guardian_auth do
      patch '/guardian_auths/confirmation' => 'guardian_auths/confirmations#update', :via => :patch, :as => :update_guardian_confirmation
  end


  resources :statistics
  resources :matches
  resources :competitions
  # Descomentar para EuroLeague
  # resources :seasons
  resources :teams
  resources :exams
  resources :guardians
  # resources :players
  resources :guardian_team_seasons, only: [:index, :show, :update]
  resources :guardian_auth_matches, only: [:update]
  resources :player_team_seasons, only: [:index, :show, :update]

  get 'guardian_auth_matches/confirm_call/:id/:m_id', to: "guardian_auth_matches#confirm_call", as: "guardian_confirm_call"
  get 'guardian_auth_matches/deny_call/:id/:m_id', to: "guardian_auth_matches#deny_call", as: "guardian_deny_call"


  resources :team_seasons do
    collection do
      get ':id/attendance', to: 'team_seasons#attendance', as: 'attendance'
    end
  end


  resources :practices do
    collection do
      post 'update_player_practice/:id', to: 'practices#update_player_practice', as: 'update_player_practice'
      post 'add_pp_late_time/:id', to: 'practices#add_late_time', as: "add_pp_late_time"
    end
  end

  get 'attendance/show/:id', to: 'attendance#show', as: 'show_attendance'

  get 'guardian_auth_players/index', as: 'guardian_index_players'
  get 'guardian_edit_player/:id', to: 'guardian_auth_players#edit', as: 'guardian_edit_player'
  post 'guardian_update_player/:id', to: 'guardian_auth_players#update', as: 'guardian_update_player'
  patch 'guardian_update_player/:id', to: 'guardian_auth_players#update'
  get 'guardian_show_player/:id', to: 'guardian_auth_players#show', as: 'guardian_show_player'

  get 'coach_guardians/edit'
  get 'coach_guardians/new'

  get 'coach_players/new', as: 'coach_new_player'
  get 'coach_players/index', to: 'coach_players#index', as: 'coach_index_players'
  get 'coach_show_player/:id', to: 'coach_players#show', as: 'coach_show_player'
  get 'coach_edit_player/:id', to: 'coach_players#edit', as: 'coach_edit_player'
  post 'coach_update_player/:id', to: 'coach_players#update', as: 'coach_update_player'
  patch 'coach_update_player/:id', to: 'coach_players#update'
  post 'coach_create_player', to: 'coach_players#create', as: 'coach_create_player'
  post 'coach_add_player_medical/:id', to: 'coach_players#add_medical', as: 'coach_add_medical'

  get 'coach_approved_photos/', to: 'photos#index_approved', as: 'index_approved'
  get 'coach_pending_photos/', to: 'photos#index_pending', as: 'index_pending'

  get 'general_pages/index', to: 'general_pages#index', as: 'general_index'
  get 'general_pages/contact', to: 'general_pages#contact', as: 'contact'
  post 'general_pages/send_contact', to: 'general_pages#send_contact', as: 'send_contact'
  get 'general_pages/about', to: 'general_pages#index', as: 'about'
  get 'general_pages/all_teams', to: 'general_pages#teams', as: 'all_teams'
  get 'general_pages/players/:id', to: 'general_pages#players', as: 'team_players'
  get 'general_pages/player/:id/:p_id', to: 'general_pages#player', as: 'gp_player'
  get 'general_pages/rankings/(:id/:c_id)', to: 'general_pages#rankings', as: 'ranking'
  get 'general_pages/calendar/:id/(:c_id)', to: 'general_pages#calendar', as: 'calendar'
  # get 'general_pages/competitions/(:id)', to: 'general_pages#competitions', as: 'all_competitions'
  # get 'general_pages/competition/:id/:c_id', to: 'general_pages#competition', as: 'show_competition'
  get 'general_pages/gallery/(team_season/:id)(/level/:level)', to: 'general_pages#photo_gallery', as: 'gallery'
  get 'general_pages/posts/(team_season/:id)(/level/:level)', to: 'general_pages#posts', as: 'all_posts'
  get 'general_pages/posts/:post_id(/team_season/:id)', to: 'general_pages#post', as: 'show_post'
  get 'general_pages/match/:m_id/team_season/:id', to: 'general_pages#match', as: 'show_match'

  post 'general_pages/change_season', to: 'general_pages#change_season', as: 'change_season'

  get 'list_documents', to: 'documents#show_documents', as: "list_documents"

  post 'add_stat_late_time/:id', to: 'statistics#add_late_time', as: "add_stat_late_time"

  get 'filter_team_seasons/:id', to: 'competitions#filter_team_seasons', as: 'filter_team_seasons'

  get 'get_team_level/:id', to: 'team_seasons#get_team_level', as: 'get_team_level'

  root 'general_pages#index'
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base

  belongs_to :match
  belongs_to :player

  validates_presence_of :player_id
  validates_presence_of :match_id
  validates_presence_of :goals
  validates :goals, numericality: { greater_than_or_equal_to: 0 }
  # :greater_than
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  before_action :authenticate_coach!
  before_action :set_statistic, only: [:show, :edit, :update, :destroy, :add_late_time]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def add_late_time
    
    @statistic.late_minutes = params[:minutes]
    @statistic.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.require(:statistic).permit(:first_yellow, :second_yellow, :red, :goals, :own_goals, :state, :called, :player_id, :match_id)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper


#   def get_player_totals(player, start_date, end_date)
#     #[g(oals), y(ellows), r(eds), o(wn)g(oals), p(layed)]
#     stats = Hash.new
#     get_states_options().each do |state|
#       stats[""+state[1].to_s] = 0
#     end
#     stats[:goals] = 0
#     stats[:yellows] = 0
#     stats[:red] = 0
#     stats[:own_goals] = 0
#     stats[:played] = 0
#     stats[:penalties] = 0
#     stats[:assists] = 0
#     stats[:played_minutes] = 0
#     stats[:stat_late_minutes] = 0
#     stats[:pp_late_minutes] = 0
#     if start_date == nil && end_date == nil
#       @matches = player.matches
#       @practices = player.practices
#     else
#       @matches = player.matches.where(match_date: start_date..end_date)
#       @practices = player.practices.where(practice_date: start_date..end_date)
#     end
#
#     @matches.each do |match|
#       stat = match.statistics.where(player_id: player.id).first
#
#       stats[""+stat.state.to_s] += 1
#       if stat.state == 3
#         stats[""+1.to_s] += 1
#       end
#       stats[:goals] += stat.goals
#
#       if stat.first_yellow
#         stats[:yellows] += 1
#       end
#       if stat.second_yellow
#         stats[:yellows] += 1
#       end
#
#       if stat.red
#         stats[:red] += 1
#       else
#         stats[:red] += 0
#       end
#       stats[:own_goals] += stat.own_goals
#       if stat.called
#         stats[:played] += 1
#       else
#         stats[:played] += 0
#       end
#       stats[:penalties] += stat.penalties
#       stats[:assists] += stat.assists
#       stats[:played_minutes] += stat.played_minutes
#       stats[:stat_late_minutes] += stat.late_minutes
#     end
#
#
#
#     @practices.each do |practice|
#       stat = practice.player_practices.where(player_id: player.id).first
#
#       stats[""+stat.state.to_s] += 1
#       if stat.state == 3
#         stats[""+1.to_s] += 1
#       end
#
#       stats[:pp_late_minutes] += stat.late_minutes
#     end
#
#   return stats
# end
#
#   def get_team_stats(team_season, start_date, end_date)
#     stats = Hash.new
#     stats[:points] = 0
#     stats[:losses] = 0
#     stats[:wins] = 0
#     stats[:draws] = 0
#     stats[:goal_diff] = 0
#     stats[:goals_for] = 0
#     stats[:goals_against] = 0
#     stats[:played] = 0
#
#
#     if start_date == nil && end_date == nil
#       @home_matches = team_season.home_matches
#       @away_matches = team_season.away_matches
#     else
#       @home_matches = team_season.home_matches.where(match_date: start_date..end_date)
#       @away_matches = team_season.away_matches.where(match_date: start_date..end_date)
#     end
#
#
#
#     @home_matches.each do |h_match|
#       if h_match.home_goals == h_match.away_goals
#         stats[:points] += 1
#         stats[:draws] += 1
#       elsif h_match.home_goals > h_match.away_goals
#         stats[:points] += 3
#         stats[:wins] += 1
#       else
#         stats[:losses] += 1
#       end
#       stats[:goals_for] += h_match.home_goals
#       stats[:goals_against] += h_match.away_goals
#     end
#
#     @away_matches.each do |a_match|
#       if a_match.away_goals == a_match.home_goals
#         stats[:points] += 1
#         stats[:draws] += 1
#       elsif a_match.away_goals > a_match.home_goals
#         stats[:points] += 3
#         stats[:wins] += 1
#       else
#         stats[:losses] += 1
#       end
#       stats[:goals_for] += a_match.away_goals
#       stats[:goals_against] += a_match.home_goals
#     end
#
#     stats[:goal_diff] = stats[:goals_for] - stats[:goals_against]
#     stats[:played] = @home_matches.size + @away_matches.size
#
#     return stats
#   end
end

app/views/statistics/_form.html.erb
<%= form_for(@statistic) do |f| %>
  <%= render partial: 'admin_partials/errors/errors_form', locals: { current_object: @statistic} %>

  <div class="field">
    <%= f.label :yellows %><br>
    <%= f.number_field :yellows %>
  </div>
  <div class="field">
    <%= f.label :red %><br>
    <%= f.check_box :red %>
  </div>
  <div class="field">
    <%= f.label :goals %><br>
    <%= f.number_field :goals %>
  </div>
  <div class="field">
    <%= f.label :own_goals %><br>
    <%= f.number_field :own_goals %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="field">
    <%= f.label :called %><br>
    <%= f.check_box :called %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :match_id %><br>
    <%= f.number_field :match_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statistics/_late_modal.html.erb
Minutos de atraso: <br>
<%= form_tag add_stat_late_time_path(s), remote: true do %>
  <%= number_field_tag :minutes %>
  <%= submit_tag "Submit"%>
<% end %>

app/views/statistics/add_late_time.js.erb
$('#late-modal').modal('toggle');

$("#statistic-state-<%= @statistic.id %>").parent().parent().children(".late-time").html("<%= @statistic.late_minutes %>");

app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<%= render "admin_partials/errors/notices" %>

<h1>Listing Statistics</h1>
<div class="table_div">
<table>
  <thead>
    <tr>
      <th>Yellows</th>
      <th>Red</th>
      <th>Goals</th>
      <th>Own goals</th>
      <th>State</th>
      <th>Called</th>
      <th>Player</th>
      <th>Match</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= statistic.yellows %></td>
        <td><%= statistic.red %></td>
        <td><%= statistic.goals %></td>
        <td><%= statistic.own_goals %></td>
        <td><%= statistic.state %></td>
        <td><%= statistic.called %></td>
        <td><%= statistic.player_id %></td>
        <td><%= statistic.match_id %></td>
        <td><%= link_to 'Show', statistic %></td>
        <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
        <td><%= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Yellows:</strong>
  <%= @statistic.yellows %>
</p>

<p>
  <strong>Red:</strong>
  <%= @statistic.red %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @statistic.goals %>
</p>

<p>
  <strong>Own goals:</strong>
  <%= @statistic.own_goals %>
</p>

<p>
  <strong>State:</strong>
  <%= @statistic.state %>
</p>

<p>
  <strong>Called:</strong>
  <%= @statistic.called %>
</p>

<p>
  <strong>Player:</strong>
  <%= @statistic.player_id %>
</p>

<p>
  <strong>Match:</strong>
  <%= @statistic.match_id %>
</p>

<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/show.js.erb
$("#statistic-state-<%= @statistic.id %>").val("<%= get_state_initial(@statistic.state) %>");
$("#statistic-state-<%= @statistic.id %>").css("background-color", "<%= get_state_colors(@statistic.state) %>");

<% if @statistic.state == 3 %>
  $('.late-form').html("<%= escape_javascript render partial: 'late_modal', locals: {s: @statistic} %>")
  $('#late-modal').modal()
<% else %>
  $('.late-form').html("")
<% end %>