config/routes.rb
Rails.application.routes.draw do

  resources :slides
  resources :sponsors
  get 'styleguide' => 'styleguide#index' if Rails.env.development?
  get 'player_matches/confirm_call/:id/:m_id', to: "player_matches#confirm_call", as: "player_confirm_call"

  get 'player_matches/deny_call/:id/:m_id', to: "player_matches#deny_call", as: "player_deny_call"

  resources :documents
  resources :schools

  get 'player_team_seasons/index'
  get 'player_team_seasons/show'

  resources :posts
  resources :photos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :coaches, :controllers => {:sessions => "coaches/sessions", :registrations => "coaches/registrations"}, skip: :registrations
  devise_scope :coach do
    resource :registration,
      only: [:edit, :update, :destroy],
      path: 'coaches',
      path_names: { new: 'sign_up' },
      controller: 'coaches/registrations',
      as: :coach_registration do
        get :cancel
    end
  end


  devise_for :player_auths,  :controllers => {:registrations => "player_auths/registrations", :confirmations => "player_auths/confirmations", :sessions => "player_auths/sessions"}, skip: :registrations
  devise_scope :player_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'player_auth',
      path_names: { new: 'sign_up' },
      controller: 'player_auths/registrations',
      as: :player_auth_registration do
        get :cancel
      end
  end
  as :player_auth do
      patch '/player_auths/confirmation' => 'player_auths/confirmations#update', :via => :patch, :as => :update_player_confirmation
  end


  devise_for :guardian_auths,  :controllers => {:registrations => "guardian_auths/registrations", :confirmations => "guardian_auths/confirmations", :sessions => "guardian_auths/sessions"}, skip: :registrations
  devise_scope :guardian_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'guardian_auth',
      path_names: { new: 'sign_up' },
      controller: 'guardian_auths/registrations',
      as: :guardian_auth_registration do
        get :cancel
      end
  end

  as :guardian_auth do
      patch '/guardian_auths/confirmation' => 'guardian_auths/confirmations#update', :via => :patch, :as => :update_guardian_confirmation
  end


  resources :statistics
  resources :matches
  resources :competitions
  # Descomentar para EuroLeague
  # resources :seasons
  resources :teams
  resources :exams
  resources :guardians
  # resources :players
  resources :guardian_team_seasons, only: [:index, :show, :update]
  resources :guardian_auth_matches, only: [:update]
  resources :player_team_seasons, only: [:index, :show, :update]

  get 'guardian_auth_matches/confirm_call/:id/:m_id', to: "guardian_auth_matches#confirm_call", as: "guardian_confirm_call"
  get 'guardian_auth_matches/deny_call/:id/:m_id', to: "guardian_auth_matches#deny_call", as: "guardian_deny_call"


  resources :team_seasons do
    collection do
      get ':id/attendance', to: 'team_seasons#attendance', as: 'attendance'
    end
  end


  resources :practices do
    collection do
      post 'update_player_practice/:id', to: 'practices#update_player_practice', as: 'update_player_practice'
      post 'add_pp_late_time/:id', to: 'practices#add_late_time', as: "add_pp_late_time"
    end
  end

  get 'attendance/show/:id', to: 'attendance#show', as: 'show_attendance'

  get 'guardian_auth_players/index', as: 'guardian_index_players'
  get 'guardian_edit_player/:id', to: 'guardian_auth_players#edit', as: 'guardian_edit_player'
  post 'guardian_update_player/:id', to: 'guardian_auth_players#update', as: 'guardian_update_player'
  patch 'guardian_update_player/:id', to: 'guardian_auth_players#update'
  get 'guardian_show_player/:id', to: 'guardian_auth_players#show', as: 'guardian_show_player'

  get 'coach_guardians/edit'
  get 'coach_guardians/new'

  get 'coach_players/new', as: 'coach_new_player'
  get 'coach_players/index', to: 'coach_players#index', as: 'coach_index_players'
  get 'coach_show_player/:id', to: 'coach_players#show', as: 'coach_show_player'
  get 'coach_edit_player/:id', to: 'coach_players#edit', as: 'coach_edit_player'
  post 'coach_update_player/:id', to: 'coach_players#update', as: 'coach_update_player'
  patch 'coach_update_player/:id', to: 'coach_players#update'
  post 'coach_create_player', to: 'coach_players#create', as: 'coach_create_player'
  post 'coach_add_player_medical/:id', to: 'coach_players#add_medical', as: 'coach_add_medical'

  get 'coach_approved_photos/', to: 'photos#index_approved', as: 'index_approved'
  get 'coach_pending_photos/', to: 'photos#index_pending', as: 'index_pending'

  get 'general_pages/index', to: 'general_pages#index', as: 'general_index'
  get 'general_pages/contact', to: 'general_pages#contact', as: 'contact'
  post 'general_pages/send_contact', to: 'general_pages#send_contact', as: 'send_contact'
  get 'general_pages/about', to: 'general_pages#index', as: 'about'
  get 'general_pages/all_teams', to: 'general_pages#teams', as: 'all_teams'
  get 'general_pages/players/:id', to: 'general_pages#players', as: 'team_players'
  get 'general_pages/player/:id/:p_id', to: 'general_pages#player', as: 'gp_player'
  get 'general_pages/rankings/(:id/:c_id)', to: 'general_pages#rankings', as: 'ranking'
  get 'general_pages/calendar/:id/(:c_id)', to: 'general_pages#calendar', as: 'calendar'
  # get 'general_pages/competitions/(:id)', to: 'general_pages#competitions', as: 'all_competitions'
  # get 'general_pages/competition/:id/:c_id', to: 'general_pages#competition', as: 'show_competition'
  get 'general_pages/gallery/(team_season/:id)(/level/:level)', to: 'general_pages#photo_gallery', as: 'gallery'
  get 'general_pages/posts/(team_season/:id)(/level/:level)', to: 'general_pages#posts', as: 'all_posts'
  get 'general_pages/posts/:post_id(/team_season/:id)', to: 'general_pages#post', as: 'show_post'
  get 'general_pages/match/:m_id/team_season/:id', to: 'general_pages#match', as: 'show_match'

  post 'general_pages/change_season', to: 'general_pages#change_season', as: 'change_season'

  get 'list_documents', to: 'documents#show_documents', as: "list_documents"

  post 'add_stat_late_time/:id', to: 'statistics#add_late_time', as: "add_stat_late_time"

  get 'filter_team_seasons/:id', to: 'competitions#filter_team_seasons', as: 'filter_team_seasons'

  get 'get_team_level/:id', to: 'team_seasons#get_team_level', as: 'get_team_level'

  root 'general_pages#index'
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  has_many :player_practices
  has_many :players, through: :player_practices

  belongs_to :team_season

  validates_presence_of :practice_date
  validates_presence_of :team_season_id
  def self.search(search, season)
    w = joins(:team_season).where("team_seasons.season_id = :season", season: season.id).where('observations ILIKE :search', search: "%#{search}%")
    i1 = joins(team_season:  :team).where('season_id = :season and name ILIKE :search', season: season.id, search: "%#{search}%")
    value = w + i1
    return value.uniq
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :authenticate_coach!
  before_action :set_practice, only: [:show, :edit, :update, :destroy]
  before_action :set_player_practice, only: [:update_player_practice, :add_late_time]

  layout 'admin'
  # GET /practices
  # GET /practices.json
  def index

    params.permit(:search)

    if session.has_key?(:current_season)
      @current_season = Season.find(session[:current_season])
    else
      @current_season = Season.last
    end


    if params[:search]
      @practices = Kaminari.paginate_array(Practice.search(params[:search], @current_season)).page(params[:page]).per(30)
    else
      @practices = []
      @current_season.team_seasons.includes(:practices, :team).each do |team_season|
        team_season.practices.each do |practice|
          @practices << practice
        end
      end
      @practices = @practices.uniq
      @practices = @practices.sort_by { |k| k[:practice_date] }.reverse!
      @practices = Kaminari.paginate_array(@practices).page(params[:page]).per(30)
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit

  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)


    respond_to do |format|
      if @practice.save

        @practice.team_season.players.each do |pp|
          player_practice = PlayerPractice.new
          player_practice.player = pp
          player_practice.practice = @practice
          player_practice.save
        end

        format.html { redirect_to @practice, notice: 'Practice was successfully created.' }
        format.json { render :show, status: :created, location: @practice }
      else
        format.html { render :new }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_player_practice
    @player_practice.update_attributes(state: params[:state])
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: 'Practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_late_time
    @player_practice.late_minutes = params[:minutes]
    @player_practice.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    def set_player_practice
      @player_practice = PlayerPractice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params.require(:practice).permit(:practice_date, :observations, :team_season_id)
    end

    def player_practice_params

      params.require(:player_practice).permit(:state)
    end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_form.html.erb
  <div class="box-body">
    <%= form_for(@practice) do |f| %>
      <%= render partial: 'admin_partials/errors/errors_form', locals: { current_object: @practice} %>

      <div class="form-group">
        <%= f.label :practice_date %><br>
        <%= f.text_field :practice_date, class: "form-control", id: "select-date", data: { date_format: 'YYYY-MM-DD HH:mm'}, required: true %>
      </div>
      <div class="form-group">
        <%= f.label :observations %><br>
        <%= f.text_area :observations, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :team_season %><br>
        <%= f.select :team_season_id, TeamSeason.includes(:team, :season).all.collect {|p| [ p.team.name + " " + p.season.start_year.to_s + "/" + p.season.end_year.to_s, p.id ] }, {}, class: "form-control"  %>
      </div>

      <div class="box-footer">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).on("ready page:load", function () {
      $('#select-date').datetimepicker(
      {
        icons: {
          time: "fa fa-clock-o",
          date: "fa fa-calendar",
          up: "fa fa-arrow-up",
          down: "fa fa-arrow-down",
          previous: "fa fa-arrow-left",
          next:  "fa fa-arrow-right"
        }
      });
  });
</script>

app/views/practices/_late_modal.html.erb
Minutos de atraso: <br>
<%= form_tag add_pp_late_time_practices_path(pp), remote: true do %>
  <%= number_field_tag :minutes %>
  <%= submit_tag "Submit"%>
<% end %>

app/views/practices/add_late_time.js.erb
$('#late-modal').modal('toggle');

$("#practice-state-<%= @player_practice.id %>").parent().parent().children(".late-time").html("<%= @player_practice.late_minutes %>");

app/views/practices/edit.html.erb
<%= render partial: 'admin_partials/edit/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.practice.edit")} %>


<%= render 'form' %>

<%= render partial: 'admin_partials/edit/footer', locals: {object_to_show: @practice, back_path: practices_path}%>

app/views/practices/index.html.erb
<%= render partial: 'admin_partials/index/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.practice.listing"),
                                                  new_path: new_practice_path,
                                                  new_button_name: t("strings.practice.new"),
                                                  search_form_path: practices_path } %>

<%= render "admin_partials/errors/notices" %>

        <div class="box-body table-responsive no-padding">
          <div class="table_div">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= t("activerecord.attributes.practice.practice_date") %></th>
                <th><%= t("activerecord.attributes.practice.observations") %></th>
                <th><%= t("activerecord.attributes.practice.team_season") %></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @practices.each do |practice| %>
                <tr>
                  <td><%= practice.practice_date.strftime("%m/%d/%Y - %H:%M") %></td>
                  <td><%= truncate(practice.observations, length: 25) %></td>
                  <td><%= practice.team_season.team.name + " - " + practice.team_season.season.start_year.to_s + "/" + practice.team_season.season.end_year.to_s  %></td>
                  <%= render partial: 'admin_partials/index/buttons', locals: { object: practice, edit_path: edit_practice_path(practice) } %>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
        </div><!-- /.box-body -->

<%= render partial: 'admin_partials/index/footer', locals: { paginate_object: @practices} %>

app/views/practices/new.html.erb
<%= render partial: 'admin_partials/new/header', locals: { section_title: params[:controller],
                                                  section_sub_title: params[:action],
                                                  page_title: "New practice" } %>


<%= render 'form' %>

<%= render partial: 'admin_partials/new/footer', locals: {back_path: practices_path}%>

app/views/practices/show.html.erb
<%= render partial: 'admin_partials/show/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.practice.show") } %>

<%= render "admin_partials/errors/notices" %>

          <strong><%= t("activerecord.attributes.practice.team_season") %></strong>
          <p class="text-muted">
            <%= @practice.team_season.team.name + "("+@practice.team_season.id.to_s+")  -  " + @practice.team_season.season.start_year.to_s + "/" + @practice.team_season.season.end_year.to_s %>
          </p>

          <strong><%= t("activerecord.attributes.practice.practice_date") %></strong>
          <p class="text-muted">
            <%= @practice.practice_date.strftime("%m/%d/%Y - %H:%M") %>
          </p>

          <strong><%= t("activerecord.attributes.practice.observations") %></strong>
          <p class="text-muted">
            <%= @practice.observations %>
          </p>
<%= render partial: 'admin_partials/show/footer', locals: {edit_path: edit_practice_path(@practice), back_path: practices_path}%>

app/views/practices/update_player_practice.js.erb
$("#practice-state-<%= @player_practice.id %>").val("<%= get_state_initial(@player_practice.state) %>");
$("#practice-state-<%= @player_practice.id %>").css("background-color", "<%= get_state_colors(@player_practice.state) %>");

<% if @player_practice.state == 3 %>
  console.log("PP 3");
  $('.late-form').html("<%= escape_javascript render partial: 'late_modal', locals: {pp: @player_practice} %>")
  $('#late-modal').modal()
<% else %>
  $('.late-form').html("")
<% end %>