config/routes.rb
Rails.application.routes.draw do

  resources :slides
  resources :sponsors
  get 'styleguide' => 'styleguide#index' if Rails.env.development?
  get 'player_matches/confirm_call/:id/:m_id', to: "player_matches#confirm_call", as: "player_confirm_call"

  get 'player_matches/deny_call/:id/:m_id', to: "player_matches#deny_call", as: "player_deny_call"

  resources :documents
  resources :schools

  get 'player_team_seasons/index'
  get 'player_team_seasons/show'

  resources :posts
  resources :photos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :coaches, :controllers => {:sessions => "coaches/sessions", :registrations => "coaches/registrations"}, skip: :registrations
  devise_scope :coach do
    resource :registration,
      only: [:edit, :update, :destroy],
      path: 'coaches',
      path_names: { new: 'sign_up' },
      controller: 'coaches/registrations',
      as: :coach_registration do
        get :cancel
    end
  end


  devise_for :player_auths,  :controllers => {:registrations => "player_auths/registrations", :confirmations => "player_auths/confirmations", :sessions => "player_auths/sessions"}, skip: :registrations
  devise_scope :player_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'player_auth',
      path_names: { new: 'sign_up' },
      controller: 'player_auths/registrations',
      as: :player_auth_registration do
        get :cancel
      end
  end
  as :player_auth do
      patch '/player_auths/confirmation' => 'player_auths/confirmations#update', :via => :patch, :as => :update_player_confirmation
  end


  devise_for :guardian_auths,  :controllers => {:registrations => "guardian_auths/registrations", :confirmations => "guardian_auths/confirmations", :sessions => "guardian_auths/sessions"}, skip: :registrations
  devise_scope :guardian_auth do
    resource :registration,
      only: [:edit, :update, :create, :destroy, :show],
      path: 'guardian_auth',
      path_names: { new: 'sign_up' },
      controller: 'guardian_auths/registrations',
      as: :guardian_auth_registration do
        get :cancel
      end
  end

  as :guardian_auth do
      patch '/guardian_auths/confirmation' => 'guardian_auths/confirmations#update', :via => :patch, :as => :update_guardian_confirmation
  end


  resources :statistics
  resources :matches
  resources :competitions
  # Descomentar para EuroLeague
  # resources :seasons
  resources :teams
  resources :exams
  resources :guardians
  # resources :players
  resources :guardian_team_seasons, only: [:index, :show, :update]
  resources :guardian_auth_matches, only: [:update]
  resources :player_team_seasons, only: [:index, :show, :update]

  get 'guardian_auth_matches/confirm_call/:id/:m_id', to: "guardian_auth_matches#confirm_call", as: "guardian_confirm_call"
  get 'guardian_auth_matches/deny_call/:id/:m_id', to: "guardian_auth_matches#deny_call", as: "guardian_deny_call"


  resources :team_seasons do
    collection do
      get ':id/attendance', to: 'team_seasons#attendance', as: 'attendance'
    end
  end


  resources :practices do
    collection do
      post 'update_player_practice/:id', to: 'practices#update_player_practice', as: 'update_player_practice'
      post 'add_pp_late_time/:id', to: 'practices#add_late_time', as: "add_pp_late_time"
    end
  end

  get 'attendance/show/:id', to: 'attendance#show', as: 'show_attendance'

  get 'guardian_auth_players/index', as: 'guardian_index_players'
  get 'guardian_edit_player/:id', to: 'guardian_auth_players#edit', as: 'guardian_edit_player'
  post 'guardian_update_player/:id', to: 'guardian_auth_players#update', as: 'guardian_update_player'
  patch 'guardian_update_player/:id', to: 'guardian_auth_players#update'
  get 'guardian_show_player/:id', to: 'guardian_auth_players#show', as: 'guardian_show_player'

  get 'coach_guardians/edit'
  get 'coach_guardians/new'

  get 'coach_players/new', as: 'coach_new_player'
  get 'coach_players/index', to: 'coach_players#index', as: 'coach_index_players'
  get 'coach_show_player/:id', to: 'coach_players#show', as: 'coach_show_player'
  get 'coach_edit_player/:id', to: 'coach_players#edit', as: 'coach_edit_player'
  post 'coach_update_player/:id', to: 'coach_players#update', as: 'coach_update_player'
  patch 'coach_update_player/:id', to: 'coach_players#update'
  post 'coach_create_player', to: 'coach_players#create', as: 'coach_create_player'
  post 'coach_add_player_medical/:id', to: 'coach_players#add_medical', as: 'coach_add_medical'

  get 'coach_approved_photos/', to: 'photos#index_approved', as: 'index_approved'
  get 'coach_pending_photos/', to: 'photos#index_pending', as: 'index_pending'

  get 'general_pages/index', to: 'general_pages#index', as: 'general_index'
  get 'general_pages/contact', to: 'general_pages#contact', as: 'contact'
  post 'general_pages/send_contact', to: 'general_pages#send_contact', as: 'send_contact'
  get 'general_pages/about', to: 'general_pages#index', as: 'about'
  get 'general_pages/all_teams', to: 'general_pages#teams', as: 'all_teams'
  get 'general_pages/players/:id', to: 'general_pages#players', as: 'team_players'
  get 'general_pages/player/:id/:p_id', to: 'general_pages#player', as: 'gp_player'
  get 'general_pages/rankings/(:id/:c_id)', to: 'general_pages#rankings', as: 'ranking'
  get 'general_pages/calendar/:id/(:c_id)', to: 'general_pages#calendar', as: 'calendar'
  # get 'general_pages/competitions/(:id)', to: 'general_pages#competitions', as: 'all_competitions'
  # get 'general_pages/competition/:id/:c_id', to: 'general_pages#competition', as: 'show_competition'
  get 'general_pages/gallery/(team_season/:id)(/level/:level)', to: 'general_pages#photo_gallery', as: 'gallery'
  get 'general_pages/posts/(team_season/:id)(/level/:level)', to: 'general_pages#posts', as: 'all_posts'
  get 'general_pages/posts/:post_id(/team_season/:id)', to: 'general_pages#post', as: 'show_post'
  get 'general_pages/match/:m_id/team_season/:id', to: 'general_pages#match', as: 'show_match'

  post 'general_pages/change_season', to: 'general_pages#change_season', as: 'change_season'

  get 'list_documents', to: 'documents#show_documents', as: "list_documents"

  post 'add_stat_late_time/:id', to: 'statistics#add_late_time', as: "add_stat_late_time"

  get 'filter_team_seasons/:id', to: 'competitions#filter_team_seasons', as: 'filter_team_seasons'

  get 'get_team_level/:id', to: 'team_seasons#get_team_level', as: 'get_team_level'

  root 'general_pages#index'
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :statistics
  has_many :players, through: :statistics

  belongs_to :away_team, class_name: "TeamSeason"
  belongs_to :home_team, class_name: "TeamSeason"

  belongs_to :competition

  has_many :photos

  accepts_nested_attributes_for :home_team
  accepts_nested_attributes_for :away_team

  accepts_nested_attributes_for :photos, allow_destroy: true

  accepts_nested_attributes_for :statistics


  validates_presence_of :home_goals
  validates_presence_of :away_goals
  validates_presence_of :away_team_id
  validates_presence_of :home_team_id

  def self.search(search, season)
    w = joins(:home_team, :away_team).where("team_seasons.season_id = :season", season: season.id).where('matchday = :md', md: search.to_i)

    i1 = joins(home_team:  :team).where('season_id = :season and name ILIKE :search', season: season.id,search: "%#{search}%")

    i2 = joins(away_team:  :team).where('season_id = :season and name ILIKE :search', season: season.id,search: "%#{search}%")

    value = w + i1 + i2

    return value.uniq
  end

  def has_happened?
    if self.match_date < Time.now
      if self.home_goals != -1 && self.away_goals != -1
        true
      else
        false
      end
    else
      false
    end
  end
end

app/models/team_season.rb
class TeamSeason < ActiveRecord::Base
  belongs_to :team

  belongs_to :season

  has_many :player_seasons
  has_many :players, :through => :player_seasons

  has_and_belongs_to_many :competitions

  has_many :away_matches, class_name: "Match", foreign_key: "away_team_id"
  has_many :home_matches, class_name: "Match", foreign_key: "home_team_id"
  has_and_belongs_to_many :coaches

  has_many :practices

  has_many :photos
  #has_and_belongs_to_many :photos

  has_and_belongs_to_many :posts

  has_and_belongs_to_many :sponsors
  accepts_nested_attributes_for :coaches, allow_destroy: true

  accepts_nested_attributes_for :player_seasons, allow_destroy: true

  accepts_nested_attributes_for :team

  accepts_nested_attributes_for :photos, allow_destroy: true
  # accepts_nested_attributes_for :player_seasons, allow_destroy: true

  validates_presence_of :team_id
  validates_presence_of :season_id

  has_attached_file :icon, styles: { medium: "300x300#", thumb: "100x100#", minithumb: "40x40#" },
    default_url: "/images/:style/missing.jpg",
    :convert_options => {
      :large => "-quality 80 -interlace Plane",
      :thumb => "-quality 80 -interlace Plane"
    },
    processors: [:thumbnail, :compression]
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\Z/


  has_attached_file :photo, styles: { banner: "1337x300#", medium: "300x300#"},
    default_url: "/images/:style/missing.jpg",
    :convert_options => {
      :large => "-quality 80 -interlace Plane",
      :thumb => "-quality 80 -interlace Plane"
    },
    processors: [:thumbnail, :compression]

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def self.search(search, season)
    joins(:team).where('season_id = :season and teams.name ILIKE :search', search: "%#{search}%", season: season.id )
  end

  def statistics(competition, start_date, end_date)
    if competition
      stats = initialize_stats()

      if start_date == nil && end_date == nil
        home_matches = self.home_matches.where(competition_id: competition.id)
        away_matches = self.away_matches.where(competition_id: competition.id)
      else
        home_matches = self.home_matches.where(match_date: start_date..end_date, competition_id: competition.id)
        away_matches = self.away_matches.where(match_date: start_date..end_date, competition_id: competition.id)
      end


      stats = calculate_stats(stats, home_matches, away_matches)


      return stats
    else
      stats = initialize_stats()

      if start_date == nil && end_date == nil
        home_matches = self.home_matches
        away_matches = self.away_matches
      else
        home_matches = self.home_matches.where(match_date: start_date..end_date)
        away_matches = self.away_matches.where(match_date: start_date..end_date)
      end


      stats = calculate_stats()



      return stats
    end
  end

  private
    def initialize_stats
      stats = Hash.new
      stats[:points] = 0
      stats[:losses] = 0
      stats[:wins] = 0
      stats[:draws] = 0
      stats[:goal_diff] = 0
      stats[:goals_for] = 0
      stats[:goals_against] = 0
      stats[:played] = 0

      return stats
    end

    def calculate_stats(stats, home_matches, away_matches)
      home_matches.each do |h_match|
        if h_match.home_goals == h_match.away_goals
          stats[:points] += 1
          stats[:draws] += 1
        elsif h_match.home_goals > h_match.away_goals
          stats[:points] += 3
          stats[:wins] += 1
        else
          stats[:losses] += 1
        end
        stats[:goals_for] += h_match.home_goals >= 0  ? h_match.home_goals : 0
        stats[:goals_against] += h_match.away_goals >= 0  ? h_match.away_goals : 0
      end

      away_matches.each do |a_match|
        if a_match.away_goals == a_match.home_goals
          stats[:points] += 1
          stats[:draws] += 1
        elsif a_match.away_goals > a_match.home_goals
          stats[:points] += 3
          stats[:wins] += 1
        else
          stats[:losses] += 1
        end
        stats[:goals_for] +=  a_match.away_goals >= 0  ? a_match.away_goals : 0
        stats[:goals_against] += a_match.away_goals >= 0  ? a_match.away_goals : 0
      end


      stats[:goal_diff] = stats[:goals_for] - stats[:goals_against]
      stats[:played] = home_matches.size + away_matches.size
      return stats
    end


end

app/helpers/matches_helper.rb
module MatchesHelper
  include TeamSeasonsHelper
  def send_called_notification(match, message)
    players = []
    if match.home_team.team.n10
      if !match.home_team.coaches.where(id: current_coach.id).blank?
        match.home_team.players.each do |player|
          if player.statistics.where(match_id: match.id).first.state == state_called_no_answer()
            if player.player_auth
              #PlayerNotificationMailer.player_called_mail(player, match, message).deliver_later
            elsif player.guardian
              if player.guardian.guardian_auth
                #GuardianNotificationMailer.player_called_mail(player, match, message).deliver_later
              elsif
                players << player.name
                # puts "No email for this player guardian".colorize(:red)
              end
            else
              players << player.name
              # puts "No email associated with this player".colorize(:red)
            end
          else
            # puts "Not called".colorize(:red)
          end
        end
        #CoachNotificationMailer.players_called_without_mail(players, current_coach).deliver_later
      else
        # puts "Home team not from coach".colorize(:red)
      end
    else
        # puts "Home team not n10.".colorize(:red)
    end
    if match.away_team.team.n10
      if !match.away_team.coaches.where(id: current_coach.id).blank?
        match.away_team.players.each do |player|
          if player.statistics.where(match_id: match.id).first.state == state_called_no_answer()
            if player.player_auth
              #PlayerNotificationMailer.player_called_mail(player, match, message).deliver_later
            elsif player.guardian
              if player.guardian.guardian_auth
                #GuardianNotificationMailer.player_called_mail(player, match, message).deliver_later
              elsif
                players << player.name
                # puts "No email for this player guardian".colorize(:red)
              end
            else
              players << player.name
              # puts "No email associated with this player".colorize(:red)
            end
          else
            # puts "Not called".colorize(:red)
          end
        end
        #CoachNotificationMailer.players_called_without_mail(players, current_coach).deliver_later
      else
        # puts "Away team not from coach".colorize(:red)
      end
    else
      # puts "Away team not n10.".colorize(:red)
    end
  end
end

app/views/matches/_new_away_team.html.erb
<%= ff.fields_for :team, Team.new do |fff| %>
  <div class="form-group">
    <%= fff.label :name %><br>
    <%= fff.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= fff.label :description %><br>
    <%= fff.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= fff.label :n10 %><br>
    <%= fff.check_box :n10 %>
  </div>

  <div class="form-group">
    <%= fff.label :level %><br>
    <% if params[:action] == "edit" %>
      <%= fff.select :level, options_for_select(get_levels_options, selected:  @team.level.to_s), {}, class: "form-control", required: true %>
    <% else %>
      <%= fff.select :level, options_for_select(get_levels_options), {}, class: "form-control", required: true %>
    <% end %>
  </div>


<% end %>

app/views/matches/_new_away_team_season.html.erb
<%= f.fields_for :away_team, TeamSeason.new do |ff| %>
  <div class="form-group">
    <%= ff.label :team %><br>
    <%= ff.select :team_id, [["Select a team", nil],["Create new team", -1]] + Team.all.collect {|p| [ p.name, p.id ] }, {}, {class:"form-control", id: "away-team-team-select", required: true} %>
  </div>

  <div class="new-away-team-form">

  </div>

  <div class="form-group">
    <%= ff.label :icon %><br>
    <%= ff.file_field :icon, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label :main_photo %><br>
    <%= ff.file_field :photo, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label "What do players and guardians get to see on the attendance board?" %><br>
    <%= ff.select :permission, options_for_select(get_permission_types()) , {}, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label :season %><br>
    <%= ff.select :season_id, Season.all.collect {|p| [ p.start_year.to_s + "/" + p.end_year.to_s, p.id ] }, {}, class:"form-control", required: true%>
  </div>

  <div class="form-group">
    <%= ff.label :coaches %><br>
    <%= ff.collection_select :coach_ids, Coach.all, :id, :name, {:include_blank => "No coach"}, {:multiple => true,class:"form-control", id:"coach-select"}  %>
  </div>


    <script>
      // Script para adicao de menu para adicionar nova team Season
      // tem de ser dentro do form para passar o f.
      $("#away-team-team-select").on('change', function() {
        if ($(this ).val() == -1){
          $(".new-away-team-form").html("<%= escape_javascript render partial: 'new_away_team', locals: {ff: ff} %>");
        }
        else {
          $(".new-away-team-form").html("");
        };

      });
    </script>

<% end %>

app/views/matches/_new_home_team.html.erb
<%= ff.fields_for :team, Team.new do |fff| %>
  <div class="form-group">
    <%= fff.label :name %><br>
    <%= fff.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= fff.label :description %><br>
    <%= fff.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= fff.label :n10 %><br>
    <%= fff.check_box :n10 %>
  </div>

  <div class="form-group">
    <%= fff.label :level %><br>
    <% if params[:action] == "edit" %>
      <%= fff.select :level, options_for_select(get_levels_options, selected:  @team.level.to_s), {}, class: "form-control", required: true %>
    <% else %>
      <%= fff.select :level, options_for_select(get_levels_options), {}, class: "form-control", required: true %>
    <% end %>
  </div>


<% end %>

app/views/matches/_new_home_team_season.html.erb
<%= f.fields_for :home_team, TeamSeason.new do |ff| %>
  <div class="form-group">
    <%= ff.label :team %><br>
    <%= ff.select :team_id, Team.all.collect {|p| [ p.name, p.id ] }.prepend(["Select a team", nil],["Create new team", -1]), {}, {class:"form-control", id: "home-team-team-select", required: true}  %>
  </div>
  <div class="new-home-team-form">

  </div>
  <div class="form-group">
    <%= ff.label :icon %><br>
    <%= ff.file_field :icon, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label :main_photo %><br>
    <%= ff.file_field :photo, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label "What do players and guardians get to see on the attendance board?" %><br>
    <%= ff.select :permission, options_for_select(get_permission_types()) , {}, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label :season %><br>
    <%= ff.select :season_id, Season.all.collect {|p| [ p.start_year.to_s + "/" + p.end_year.to_s, p.id ] }, {}, class:"form-control", required: true%>
  </div>

  <div class="form-group">
    <%= ff.label :coaches %><br>
    <%= ff.collection_select :coach_ids, Coach.all, :id, :name, {:include_blank => "No coach"}, {:multiple => true,class:"form-control", id:"coach-select"}  %>
  </div>

  <script>
    // Script para adicao de menu para adicionar nova team Season
    // tem de ser dentro do form para passar o f.
    $("#home-team-team-select").on('change', function() {
      if ($(this ).val() == -1){
        $(".new-home-team-form").html("<%= escape_javascript render partial: 'new_home_team', locals: {ff: ff} %>");
      }
      else {
        $(".new-home-team-form").html("");
      };

    });
  </script>


<% end %>

app/views/matches/index.html.erb
<%= render partial: 'admin_partials/index/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.match.listing"),
                                                  new_path: new_match_path,
                                                  new_button_name: t("strings.match.new"),
                                                  search_form_path: matches_path } %>

<%= render "admin_partials/errors/notices" %>

        <div class="box-body table-responsive no-padding">
          <div class="table_div">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= t("activerecord.attributes.match.matchday") %></th>
                <th><%= t("activerecord.attributes.match.home_team") %> </th>
                <th><%= t("activerecord.attributes.match.home_goals") %></th>
                <th><%= t("activerecord.attributes.match.away_goals") %></th>
                <th><%= t("activerecord.attributes.match.away_team") %> </th>
                <th><%= t("activerecord.attributes.match.match_date") %></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @matches.each do |match| %>
                <tr>
                  <td><%= match.matchday %></td>
                  <td><%= match.home_team.team.name %></td>
                  <td><%= match.home_goals %></td>
                  <td><%= match.away_goals %></td>
                  <td><%= match.away_team.team.name %></td>
                  <td><%= match.match_date.strftime("%m/%d/%Y - %H:%M") %></td>
                  <%= render partial: 'admin_partials/index/buttons', locals: { object: match, edit_path: edit_match_path(match) } %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        </div><!-- /.box-body -->

<%= render partial: 'admin_partials/index/footer', locals: { paginate_object: @matches} %>

app/views/matches/show.html.erb
<%= render partial: 'admin_partials/content_header', locals: {section_title: t("controller."+params[:controller]), section_sub_title: t("action."+params[:action])} %>

<!-- Main content -->
<section class="content">
    <!-- Header -->
  <div class="box box-default">
    <div class="box-header with-border">
      <h3 class="box-title"> <i class="fa fa-futbol-o"></i> <%= t("activerecord.attributes.match.matchday") + " " +  @match.matchday.to_s %>  | <%= @match.match_date.strftime("%m/%d/%Y - %H:%M") %>
      </h3>
    </div>

    <div class="box-body">

      <%= render "admin_partials/errors/notices" %>

      <div class="col-md-1"></div>
      <div class="col-md-2">
        <%= @match.home_team.team.name %>
      </div>
      <div class="col-md-1">
        -
      </div>
      <div class="col-md-2">
        <%= @match.home_goals %>
      </div>
      <div class="col-md-1">
        x
      </div>
      <div class="col-md-2">
        <%= @match.away_goals %>
      </div>
      <div class="col-md-1">
        -
      </div>
      <div class="col-md-2">
        <%= @match.away_team.team.name %>
      </div>
    </div>
  </div>

  <div class="row">
    <!-- Home Team -->
    <div class="col-md-6">
      <div class="box box-default">
        <div class="box-header with-border">
          <i class="fa fa-shield"></i>
          <h3 class="box-title"><%= @match.home_team.team.name %></h3>
        </div><!-- /.box-header -->

        <div class="box-body">



          <strong><%= t("strings.match.home_team_players") %></strong>
          <br>
          <p>
            <div class="table_div">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th><%= t("strings.match.player") %></th>
                  <th><%= t("strings.match.goals") %></th>
                  <th><%= t("strings.match.penalties") %></th>
                  <th><%= t("strings.match.assists") %></th>
                  <th><%= t("strings.match.played_minutes") %> </th>
                  <th><%= t("strings.match.yellows") %></th>
                  <th><%= t("strings.match.red") %></th>
                  <th><%= t("strings.match.own_goals") %> </th>
                  <th><%= t("strings.match.state") %></th>
                </tr>
              </thead>
              <tbody>
                <% @match.home_team.players.each do |player| %>
                  <tr>
                    <% player_stat = player.statistics.where(match_id: @match.id).first %>
                    <td><%= link_to player.name, coach_show_player_path(player) %></td>
                    <td><%= player_stat ? player_stat.goals : "n/i" %></td>
                    <td><%= player_stat ? player_stat.penalties : "n/i"  %></td>
                    <td><%= player_stat ? player_stat.assists : "n/i"  %></td>
                    <td><%= player_stat ? player_stat.played_minutes : "n/i"  %></td>
                    <td><%= player_stat ? player_stat.first_yellow &&  player_stat.second_yellow ? "2" : player_stat.first_yellow || player_stat.second_yellow ? "1" : "0"  : "n/i" %> </td>
                    <td><%= player_stat ? player_stat.red ? "1" : "0"  : "n/i" %></td>
                    <td><%= player_stat ? player_stat.own_goals  : "n/i" %></td>
                    <td><%= player_stat ? get_state(player_stat.state)  : "n/i" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            </div>
          </p>

          <strong><%= t("activerecord.attributes.match.home_observations") %></strong>
          <p class="text-muted">
            <%= @match.home_observations %>
          </p>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->

    <!-- Away Team -->
    <div class="col-md-6">
      <div class="box box-default">
        <div class="box-header with-border">
          <i class="fa fa-shield"></i>
          <h3 class="box-title"><%= @match.away_team.team.name %></h3>
        </div><!-- /.box-header -->

        <div class="box-body">


          <strong><%= t("strings.match.away_team_players") %></strong>
          <br>
          <p>
            <div class="table_div">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th><%= t("strings.match.player") %></th>
                  <th><%= t("strings.match.goals") %></th>
                  <th><%= t("strings.match.penalties") %></th>
                  <th><%= t("strings.match.assists") %></th>
                  <th><%= t("strings.match.played_minutes") %> </th>
                  <th><%= t("strings.match.yellows") %></th>
                  <th><%= t("strings.match.red") %></th>
                  <th><%= t("strings.match.own_goals") %> </th>
                  <th><%= t("strings.match.state") %></th>
                </tr>
              </thead>
              <tbody>
                <% @match.away_team.players.each do |player| %>
                  <tr>
                    <% player_stat = player.statistics.where(match_id: @match.id).first %>
                    <td><%= link_to player.name, coach_show_player_path(player) %></td>
                    <td><%= player_stat ? player_stat.goals : "n/i" %></td>
                    <td><%= player_stat ? player_stat.penalties : "n/i"  %></td>
                    <td><%= player_stat ? player_stat.assists : "n/i"  %></td>
                    <td><%= player_stat ? player_stat.played_minutes : "n/i"  %></td>
                    <td><%= player_stat ? player_stat.first_yellow &&  player_stat.second_yellow ? "2" : player_stat.first_yellow || player_stat.second_yellow ? "1" : "0"  : "n/i" %> </td>
                    <td><%= player_stat ? player_stat.red ? "1" : "0"  : "n/i" %></td>
                    <td><%= player_stat ? player_stat.own_goals  : "n/i" %></td>
                    <td><%= player_stat ? get_state(player_stat.state)  : "n/i" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            </div>
          </p>

          <strong><%= t("activerecord.attributes.match.away_observations") %></strong>
          <p class="text-muted">
            <%= @match.away_observations %>
          </p>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->
  </div>

  <!-- Observations and Aditional Information -->
  <div class="box box-default">
    <div class="box-body">
      <strong><%= t("activerecord.attributes.match.delegate1") %></strong>
      <p class="text-muted">
        <%= @match.delegate1 %>
      </p>


      <strong><%= t("activerecord.attributes.match.delegate2") %></strong>
      <p class="text-muted">
        <%= @match.delegate2 %>
      </p>

      <strong><%= t("activerecord.attributes.match.referee1") %></strong>
      <p class="text-muted">
        <%= @match.referee1 %>
      </p>

      <strong><%= t("activerecord.attributes.match.referee2") %></strong>
      <p class="text-muted">
        <%= @match.referee2 %>
      </p>

      <strong><%= t("activerecord.attributes.match.referee3") %></strong>
      <p class="text-muted">
        <%= @match.referee3 %>
      </p>


      <strong><%= t("activerecord.attributes.match.ref_observations") %></strong>
      <p class="text-muted">
        <%= @match.ref_observations %>
      </p>

    </div>
  </div>

  <div class="box box-default">
    <div class="box-body">
      <%= link_to t("strings.admin.edit"), edit_match_path(@match) %> |
      <%= link_to t("strings.admin.back"), matches_path %>
    </div>
  </div>
</section>